chains:
  - id: 1
    name: Ethereum
    is_enabled: true
    covalent_name: eth-mainnet
    rpc_url_env_name: ETHEREUM_RPC_URL
  - id: 42161
    name: Arbitrum
    covalent_name: arbitrum-mainnet
    is_enabled: true
    rpc_url_env_name: ARBITRUM_RPC_URL
  - id: 10
    name: Optimism
    is_enabled: true
    covalent_name: optimism-mainnet
    rpc_url_env_name: OPTIMISM_RPC_URL
  - id: 8453
    name: Base
    is_enabled: true
    covalent_name: base-mainnet
    rpc_url_env_name: BASE_RPC_URL
tokens:
  - symbol: USDC
    is_enabled: true
    coingecko_symbol: usd-coin
    by_chain:
      1:
        is_enabled: true
        decimals: 6
        address: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
      42161:
        is_enabled: true
        decimals: 6
        address: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
  - symbol: USDT
    is_enabled: true
    coingecko_symbol: tether
    by_chain:
      1:
        is_enabled: true
        decimals: 6
        address: '0xdac17f958d2ee523a2206206994597c13d831ec7'
      42161:
        is_enabled: true
        decimals: 6
        address: '0xaf88d065e77c8cC2239327C5EDb3A432268e5831'
buckets:
  - from_chain_id: 1
    to_chain_id: 42161
    from_token: USDC
    to_token: USDC
    is_smart_contract_deposit_supported: false
    token_amount_from_usd: 1
    token_amount_to_usd: 10
  - from_chain_id: 1
    to_chain_id: 42161
    from_token: USDC
    to_token: USDC
    is_smart_contract_deposit_supported: false
    token_amount_from_usd: 10
    token_amount_to_usd: 100
  - from_chain_id: 1
    to_chain_id: 42161
    from_token: USDC
    to_token: USDC
    is_smart_contract_deposit_supported: false
    token_amount_from_usd: 100
    token_amount_to_usd: 1000
  - from_chain_id: 1
    to_chain_id: 42161
    from_token: USDC
    to_token: USDC
    is_smart_contract_deposit_supported: false
    token_amount_from_usd: 1000
    token_amount_to_usd: 10000
  - from_chain_id: 1
    to_chain_id: 42161
    from_token: USDC
    to_token: USDC
    is_smart_contract_deposit_supported: false
    token_amount_from_usd: 10000
    token_amount_to_usd: 100000
bungee:
  base_url: https://api.socket.tech/v2
covalent:
  base_url: "https://api.covalenthq.com"
coingecko:
  base_url: "https://api.coingecko.com/api/v3"
  expiry_sec: 300
server:
  port: 8080
  host: "localhost"
indexer_config:
  indexer_update_topic: indexer_update
  indexer_update_message: message
  points_per_bucket: 10
solver_config:
  x_value: 2.0
  y_value: 1.0
