[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "2.8.2"
tokio = { version = "1.38.0", features = ["full"] }
futures = "0.3.30"
serde = { version = "1.0.203", features = ["derive"] }
