[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[dependencies]
config = { path = "../config" }
redis = { version = "0.25.4", features = ["aio", "tokio-comp"] }
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["macros", "rt"] }
