name: reflux
namespace: "reflux"
image_name: "us-docker.pkg.dev/biconomy-prod/biconomy-prod/reflux"
image_tag: "latest"
imagePullPolicy: Always
port: 8000
replica: 2

resource:
  requests:
    memory: 16Gi
    cpu: 4
  limits:
    memory: 32Gi
    cpu: 8

autoscale:
  enable: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

config:
  ENV: "production"
  config.toml: |
      chains:
        - id: 1
          name: Ethereum
          covalent_name: eth-mainnet
          is_enabled: true
        - id: 42161
          name: Arbitrum
          is_enabled: true
          covalent_name: bsc-mainnet
      tokens:
        - symbol: USDC
          is_enabled: true
          coingecko_symbol: usd-coin
          by_chain:
            1:
              is_enabled: true
              decimals: 6
              address: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48'
            42161:
              is_enabled: true
              decimals: 6
              address: '0xaf88d065e77c8cC2239327C5EDb3A432268e5831'
      buckets:
        - from_chain_id: 1
          to_chain_id: 42161
          from_token: USDC
          to_token: USDC
          is_smart_contract_deposit_supported: false
          token_amount_from_usd: 1
          token_amount_to_usd: 10
        - from_chain_id: 1
          to_chain_id: 42161
          from_token: USDC
          to_token: USDC
          is_smart_contract_deposit_supported: false
          token_amount_from_usd: 10
          token_amount_to_usd: 100
        - from_chain_id: 1
          to_chain_id: 42161
          from_token: USDC
          to_token: USDC
          is_smart_contract_deposit_supported: false
          token_amount_from_usd: 100
          token_amount_to_usd: 1000
        - from_chain_id: 1
          to_chain_id: 42161
          from_token: USDC
          to_token: USDC
          is_smart_contract_deposit_supported: false
          token_amount_from_usd: 1000
          token_amount_to_usd: 10000
        - from_chain_id: 1
          to_chain_id: 42161
          from_token: USDC
          to_token: USDC
          is_smart_contract_deposit_supported: false
          token_amount_from_usd: 10000
          token_amount_to_usd: 100000
      bungee:
        base_url: https://api.socket.tech/v2
      covalent:
        base_url: ''
      coingecko:
        base_url: https://api.coingecko.com/api/v3
        expiry_sec: 300
      infra:
        redis_url: redis://localhost:6379
        mongo_url: mongodb://127.0.0.1:27017
      server:
        port: 8080
        host: localhost
      indexer_config:
        indexer_update_topic: indexer_update
        indexer_update_message: message
        points_per_bucket: 3
      solver_config:
        x_value: 2.0
        y_value: 1.0

secret:
  projectID: biconomy-prod
  key: reflux
  data:
    TOKEN:
      name: TOKEN
      version: latest
      property: TOKEN

ingress:
  host: reflux.prod.biconomy.io

probes:
  healthEndpoint: /health
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3

cronjob:
  schedule: "0 */5 * * *"
  command:
    - reflux
    - --indexer
    - --config
    -  "/usr/local/cargo/config.toml" 
  restartPolicy: OnFailure


datadog:
  enable: true
  env: "production"

  service: "reflux"
  version: "v0.0.10"
  lib_version: "v0.0.1"

  configs:
    DD_TRACE_AGENT_URL: "unix:///var/run/datadog/apm.socket"
    DD_ENV: "production"
    DD_SERVICE: "reflux"
    DD_VERSION: "v0.0.1"
    DD_LIB_VERSION: "v0.0.1"
    DD_TRACE_DEBUG: "false"
    DD_TRACE_STARTUP_LOGS: "false"
    DD_PROFILING_ENABLED: "true"
    DD_LOGS_INJECTION: "false"
    DD_RUNTIME_METRICS_ENABLED: "true"
