[package]
name = "routing-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.203"
tokio = { version = "1.38.0", features = ["full"] }

# workspace dependencies
account-aggregation = { workspace = true }
