apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "reflux.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Values.config | toYaml | indent 4 }}
