apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.name }}-indexer
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    {{- include "reflux.labels" . | nindent 4 }}
  {{- if .Values.datadog.enable }}
    {{- include "datadog.datatrace" $ | nindent 4 }}
  {{- end }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
            labels:
                app: {{ .Values.name }}
        spec:
          containers:
          - name: {{ .Values.name }}
            image: {{ .Values.image_name }}:{{ .Values.image_tag }}
            imagePullPolicy: {{ .Values.imagePullPolicy }}
            envFrom:
              - secretRef:
                    name: {{ .Values.name }}
            command:
              - /bin/sh
              - '-c'
            args:
              - reflux --indexer --config config.yaml
            volumeMounts:
              - name: config-volume
                mountPath: /home/nonroot/reflux/config.yaml
                subPath: config.yaml
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          volumes:
            - name: config-volume
              configMap:
                name: {{ .Values.name }}
