apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "reflux.labels" . | nindent 4 }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.secret.projectID }}
  data:
  {{- range $key, $value := .Values.secret.data }}
  - key: {{ $.Values.secret.key }}
    name: {{ $value.name }}
    version: {{ $value.version }}
    property: {{ $value.property }}
  {{- end }}
