[package]
name = "reflux"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
tower-http = { version = "0.5.2", features = ["cors"] }
mongodb = "2.8.2"
dotenv = "0.15.0"
axum = "0.7.5"
api = { workspace = true }
log = "0.4.21"

# workspace dependencies
account-aggregation = { workspace = true }
storage = { workspace = true }
config = { workspace = true }
