[package]
name = "reflux"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
tower-http = { version = "0.5.2", features = ["cors"] }
axum = "0.7.5"
log = "0.4.21"
simple_logger = "5.0.0"
clap = { version = "4.5.7", features = ["derive"] }
dotenv = "0.15.0"
futures-util = "0.3.30"

# workspace dependencies
account-aggregation = { workspace = true }
storage = { workspace = true }
config = { workspace = true }
routing-engine = { workspace = true }
api = { workspace = true }
thiserror = "1.0.61"
