name: Test Suite
on: [pull_request, push]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:v5.0.12
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Wait for MongoDB to be ready
        run: |
          for i in {1..30}; do
            if mongo --eval "db.runCommand({ ping: 1 })"; then
              echo "MongoDB is ready"
              break
            fi
            echo "Waiting for MongoDB to be ready..."
            sleep 5
          done

      - name: Run Tests
        run: cargo test --all-features
