name: Test Suite
on: [pull_request, push]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval=30s
          --health-timeout=10s
          --health-retries=10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

    env:
      BUNGEE_API_KEY: ${{ secrets.BUNGEE_API_KEY }}
    environment: Testing
